import { Container, Header } from '@/shared/components/shared';

export const metadata = {
	title: 'Next Game | Корзина',
	description: 'Generated by Next.js',
};

export default function CheckoutLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<main className="min-h-screen bg-[#f5f5ff]">
			<Container>
				<Header
					className="border-b-gray-200"
					hasSearch={false}
					hasCart={false}
				/>
				{children}
			</Container>
		</main>
	);
}
